

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bank?serverTimezone=UTC
#    username: root
#    password: '0000'

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bank?serverTimezone=UTC
      username: root
      password: '0000'